### ISSUE TITLE
(Feature request) Automatically remove screenshot after stats are identified

### ISSUE THREAD

**Issue by jmsether** [BraisGabin/pokescreenshot#10]
I think it would be a nice to remove the screenshots after stats are show as to not cludder up the photo library. Maybe make this togglable? Also nice work man :)

**Comment by BraisGabin** [comment]
You are completely right. I'll add this feature as soon as possible.

**Comment by jmsether** [comment]
Sweet :) you da man. Thanks for all your hard work.
