### ISSUE TITLE
Doesn't work on Nexus 5X

### ISSUE THREAD

**Issue by Blaisorblade** [BraisGabin/pokescreenshot#13]
Hi! I gave your app a try but it doesn't work for me, *and* I don't get options to send you unrecognized images.

I started the app, took screenshots of PoGo Pokemon screens on 5X, and nothing happened, even on logcat (filtering for `braisg` at Verbose level). I've tried a few times and always nothing happened.
I haven't had time to debug this. GoIV detects the screenshot just fine after a visible delay.

I could only look at one thing: the screenshot code, since it's caused us problems on some phones, and since I didn't even get errors about failures in image recognition.

The screenshot code seems a bit more fragile with timing since it requires screenshots from the past 2 seconds. I am not sure that should be the problem on a Nexus 5X, but screenshots are huge, so I won't bet against it:
https://github.com/BraisGabin/pokescreenshot/blob/master/app/src/main/java/com/braisgabin/pokescreenshot/ScreenshotObservable.java

FWIW, we use a similar API but have a longer delay and detect it later, but I'm not the one who wrote/debugged the code.
https://github.com/farkam135/GoIV/blob/327d244c7fc511af5a17f372cac86ef1b5456e4e/app/src/main/java/com/kamron/pogoiv/ScreenShotHelper.java

FWIW: these delays assume bounded-time message delivery in something similar to a distributed systems (OK not really), so both are faulty heuristics. Hence, IMHO should probably be coded defensively.

**Comment by BraisGabin** [comment]
Thanks for the report. It turns out that it doesn't work in my Nexus 6P neigther...

The documentation about `ContentProvider`s and `ContentResolver`s is really crappy...

**Comment by Blaisorblade** [comment]
Just tested, works now, modulo the new PoGo interface—but I did get to send you a report.
